name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write


jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set short SHA
        id: vars
        run: echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        run: |
          docker build \
            -t personalportfolio:${{ steps.vars.outputs.short_sha }} \
            .

      - name: Save Docker image
        run: |
          docker save myapp:${{ steps.vars.outputs.short_sha }} \
            | gzip > myapp-${{ steps.vars.outputs.short_sha }}.tar.gz

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${{ steps.vars.outputs.short_sha }}" \
            "myapp-${{ steps.vars.outputs.short_sha }}.tar.gz" \
            --title "Release ${{ steps.vars.outputs.short_sha }}" \
            --generate-notes